accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_view
from .views import *

urlpatterns = [
    path('login/', auth_view.LoginView.as_view(), name='login'),
    path('logout/', auth_view.LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
    path('register/', register, name='register')
]

bookmark/urls.py
from django.urls import path
from django.contrib.auth import views as auth_view
from .views import *
from accounts import forms

urlpatterns = [
    path('', BookmarkListView.as_view(), name='list'),
    #  2nd url       View               template name
    path("add/", BookmarkCreateView.as_view(), name='add'),
    path("detail/<int:pk>/", BookmarkDetailView.as_view(), name='detail'),
    # int:pk  =  (primary key) 북마크의 글번호!, 슬러그 형태 (함수이름같이 만든거 how to press)
    path("update/<int:pk>/", BookmarkUpdateView.as_view(), name='update'),
    path("delete/<int:pk>/", BookmarkDeleteView.as_view(), name='delete'),
]

common/urls.py
urlpatterns = [
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_page.urls')),
    path('bookmark/', include('bookmark.urls')),
    path('accounts/', include('accounts.urls')),
    path('common/', include('common.urls')),
    path('photo/', include('photo.urls')),
]

handler404 = 'common.views.page_not_found'

main_page/urls.py
from django.urls import path
from django.contrib.auth import views as auth_view
from .views import *
from accounts import forms

urlpatterns = [
    path('', display, name='main'),
]

photo/urls.py
from django.urls import path
from .views import *

app_name = 'photo'

urlpatterns = [
    path('', photo_list, name='photo_list'),
    path('detail/<int:pk>/', PhotoDetailView.as_view(), name='photo_detail'),
    path('upload/', PhotoUploadView.as_view(), name='photo_upload'),
    path('delete/<int:pk>/', PhotoDeleteView.as_view(), name='photo_delete'),
    path('update/<int:pk>/', PhotoUpdateView.as_view(), name='photo_update'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

bookmark/models.py
from django.db import models
from django.urls import reverse

# Create your models here.


class Bookmark(models.Model):
    site_name = models.CharField(max_length=100)
    url = models.URLField('Site URL')

    def __str__(self):
        return "이름 : " +self.site_name+", 주소 : " + self.url

    def get_absolute_url(self):
        return reverse('detail', args=[self.id])

common/models.py
from django.db import models

# Create your models here.

photo/models.py
from django.db import models
from django.urls import reverse
# Create your models here.

from django.contrib.auth.models import User

class Photo(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_photos')
    photo = models.ImageField(upload_to='photos/%Y/%m/%d', default='photos/no_image.png')
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-updated']

    def __str__(self):
        return self.author.username + " " + self.created.strftime("%Y-%m-%d %H:%M:%S")

    def get_absolute_url(self):
        return reverse('photo:photo_detail', args=[self.id])

accounts/forms.py
from django.contrib.auth.models import User
from django import forms

# 폼 : 폼태그 -> HTML의 태그 -> 프론트단에서 사용자의 입력을 받는 인터페이스
# 장고의 폼 : HTML의 폼, 데이터 베이스에 저장할 내용을 형식, 제약조건을 설정


class RegisterForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat Password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords not matched!')
        return cd['password2']

accounts/views.py
from django.shortcuts import render
from .forms import RegisterForm

# Create your views here.


def register(request):
    if request.method == "POST":
        # 회원가입 데이터 입력 완료
        user_form = RegisterForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            return render(request, 'registration/register_done.html', {'new_user':new_user})
    else:
        # 회원가입 내용을 입력하는 상황
        user_form = RegisterForm()

    return render(request, 'registration/register.html', {'form':user_form})

bookmark/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from django.core.paginator import Paginator
from django.urls import reverse_lazy
from .models import Bookmark

"""
함수형 뷰 페이지네이션
@login_required
def paging(request):
    model_list = Bookmark.objects.all()
    paginator = Paginator(model_list, 5)
    page = request.GET.get('page')
    page_obj = paginator.get_page(page)

    return render(request, 'bookmark_list.html', {'bookmark': page_obj})
"""

class BookmarkListView(LoginRequiredMixin, ListView):
    model = Bookmark  # need Model attr
    paginate_by = 5                    # 제너릭뷰 페이지네이션
    queryset = Bookmark.objects.all()  # 제너릭뷰 페이지네이션


class BookmarkCreateView(CreateView): # create / update 뷰들은 어떤 내용을 수정할 건지 알려주는 field가 필요하다
    model = Bookmark
    fields = ['site_name', 'url']
    success_url = reverse_lazy('list')
    template_name_suffix = '_create'


class BookmarkDetailView(LoginRequiredMixin, DetailView):
    model = Bookmark


class BookmarkUpdateView(LoginRequiredMixin, UpdateView):
    model = Bookmark
    fields = ['site_name', 'url']
    template_name_suffix = '_update'

class BookmarkDeleteView(LoginRequiredMixin, DeleteView):
    model = Bookmark
    success_url = reverse_lazy('list')

common/views.py
from django.shortcuts import render

# Create your views here.


def page_not_found(request, exception):
    """
    404 Page not found
    """
    return render(request, 'common/404.html', {})

main_page/views.py
from django.shortcuts import render

# Create your views here.


def display(request):
    return render(request, 'main.html')

photo/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.detail import DetailView
from .models import Photo
from django.contrib.auth.decorators import login_required   # 제너릭
from django.contrib.auth.mixins import LoginRequiredMixin   # 함수형뷰


# Create your views here.
@login_required
def photo_list(request):
    photos = Photo.objects.all()
    return render(request, 'photo/list.html', {'photos' : photos})
#                           template     {template 내의 이름 : python 변수}


class PhotoDetailView(LoginRequiredMixin, DeleteView):
    model = Photo
    template_name = 'photo/detail.html'


class PhotoUploadView(LoginRequiredMixin, CreateView):
    model = Photo
    fields = ['photo', 'text']
    template_name = 'photo/upload.html'

    def form_valid(self, form):
        form.instance.author_id = self.request.user.id
        if form.is_valid():
            form.instance.save()
            return redirect('/')
        else:
            return self.render_to_response({'form' : form})


class PhotoDeleteView(LoginRequiredMixin, DeleteView):
    model = Photo
    success_url = '/'
    template_name = 'photo/delete.html'


class PhotoUpdateView(LoginRequiredMixin, UpdateView):
    model = Photo
    fields = ['photo', 'text']
    template_name = 'photo/update.html'

bookmark/templates/bookmark/bookmark_confirm_delete.html
{% extends 'base.html' %}
{% block title%}Confirm Delete{% endblock %}
{% block content %}
    <form action="" method="post">
        {%csrf_token%}
        <div class="aler alert-danger">Do you want to delete Bookmark "{{object}}?</div>
        <input type="submit" value="Delete" class="btn btn-danger">
    </form>
{% endblock %}

bookmark/templates/bookmark/bookmark_create.html
{% extends 'base.html' %}
{% block title%}Bookmark Add{% endblock %}
{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Add" class="btn btn-info btn-sm">
</form>
{% endblock %}

bookmark/templates/bookmark/bookmark_detail.html
{% extends 'base.html' %}
{% block title%}Detail{% endblock %}
{% block content %}
{{object.site_name}}<br/>
{{object.url}}
{% endblock %}

bookmark/templates/bookmark/bookmark_list.html
{% extends 'base.html' %}
{% block title%}Bookmark List{% endblock %}
{% block content %}
<div class="btn-group">
    <a href="{% url 'add' %}" class="btn btn-info">Add Bookmark</a>
</div>
<p></p>
<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Site</th>
            <th scope="col">URL</th>
            <th scope="col">Modify</th>
            <th scope="col">Delete</th>
        </tr>
    </thead>

    <tbody>
        {% for bookmark in object_list%}
            <tr>
                <td>{{forloop.counter}}</td>
                <td><a href="{% url 'detail' pk=bookmark.id%}">{{bookmark.site_name}}</a></td>
                <td><a href="{{bookmark.url}}" target="_blank">{{bookmark.url}}</a></td>
                <td><a href="{% url 'update' pk=bookmark.id%}" class="btn btn-success btn-sm">Modify</a></td>
                <td><a href="{% url 'delete' pk=bookmark.id%}" class="btn btn-danger btn-sm">Delete</a></td>
            </tr>
        {% endfor %}
    </tbody>
</table>
    <div id="paging">
    <ul class="pagination justify-content-center" style="margin-top: 2rem;">
        <!-- 이전페이지 -->
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in page_obj.paginator.page_range %}
            {% if page_number == page_obj.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    </div>
{% endblock %}

bookmark/templates/bookmark/bookmark_update.html
{% extends 'base.html' %}
{% block title%}Bookmark Add{% endblock %}
{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{form.as_p}}
    <input type="submit" value="Update" class="btn btn-info btn-sm">
    </form>
{% endblock %}

main_page/templates/main.html
{% extends 'base.html' %}
{% block title%}Main{% endblock %}
{% block content %}
{% endblock %}

photo/templates/photo/delete.html
{% extends 'base.html' %}
{% block title%}- Delete{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <div class="alert alert-info">
                Do you want to delete {{object}}?
            </div>
            <form action="" method="post">
                {{form.as_p}}
                {%csrf_token%}
                <input type="submit" class="btn btn-primary" value="Confirm">
            </form>

        </div>
        <div class="col-md-2"></div>
    </div>
{% endblock %}

photo/templates/photo/detail.html
{% extends 'base.html' %}
{% block title%}
    {{object.text|truncatechars:10}}
{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8 panel panel-default">
            <p><img src="{{object.photo.url}}" style="width:100%;"></p>
            <button type="button" class="btn btn-xs btn-info">
                {{object.author.username}}
            </button>
            <p>{{object.text|linebreaksbr}}</p>
            <a href="{% url 'photo:photo_delete' pk=object.id %}" class="btn btn-outline-danger btn-sm float-right">Delete</a>
            <a href="{% url 'photo:photo_update' pk=object.id %}" class="btn btn-outline-success btn-sm float-right">Update</a>
        </div>
        <div class="col-md-2"></div>
    </div>
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            {% load disqus_tags %}
            {% disqus_show_comments %}
        </div>
        <div class="col-md-2"></div>
    </div>
{% endblock %}

photo/templates/photo/list.html
{% extends 'base.html' %}
{% block title%}- List{% endblock %}

{% block content %}
{% for post in photos %}
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8 panel panel-default">
            <p><img src="{{post.photo.url}}" style="width:100%;"></p>
            <button type="button" class="btn btn-xs btn-info">
                {{post.author.username}}
            </button>
            <p>{{post.text|linebreaksbr}}</p>
            <p class="text-right">
                <a href="{% url 'photo:photo_detail' pk=post.id %}" class="btn btn-xs btn-success">댓글달기</a>
            </p>
        </div>
        <div class="col-md-2"></div>
    </div>
{% endfor %}
{% endblock %}

photo/templates/photo/update.html
{% extends 'base.html' %}
{% block title%}- Update{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <form action="" method="post" enctype="multipart/form-data">
                {{form.as_p}}
                {%csrf_token%}
                <input type="submit" class="btn btn-primary" value="Update">
            </form>

        </div>
        <div class="col-md-2"></div>
    </div>
{% endblock %}

photo/templates/photo/upload.html
{% extends 'base.html' %}
{% block title%}- Upload{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <form action="" method="post" enctype="multipart/form-data">
                {{form.as_p}}
                {%csrf_token%}
                <input type="submit" class="btn btn-primary" value="Upload">
            </form>

        </div>
        <div class="col-md-2"></div>
    </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}?{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</head>
<body>
<div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
            {% if user.is_authenticated %}
          <a class="navbar-brand" href="/">{{user.get_username}} Page</a>
            <li class="nav-item"><a href="{% url 'list' %}" class="nav-link">Bookmark</a></li>
            <li class="nav-item"><a href="/" class="nav-link">Other App</a></li>
            <li class="nav-item"><a href="/" class="nav-link">Welcome, {{user.get_username}}</a></li>
            <li class="nav-item"><a href="{% url 'logout' %}" class="nav-link">Logout</a></li>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Home</a>
                    </li>
                    <li class="nav-item">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Link
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="{% url 'list' %}">Bookmark</a></li>
                                <li><a class="dropdown-item" href="{ % %}">Something Else</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" href="#">Something else here</a></li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Dropdown
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="#">Action</a></li>
                                <li><a class="dropdown-item" href="#">Another action</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" href="#">Something else here</a></li>
                            </ul>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link disabled">Disabled</a>
                        </li>
                 </ul>
                 <form class="d-flex">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                 </form>
          {% else %}
          <a class="navbar-brand" href="/">Main Page</a>
            <li class="nav-item"><a href="{% url 'login' %}" class="nav-link">Login</a></li>
            <li class="nav-item"><a href="{% url 'register' %}" class="nav-link">Signup</a></li>
          {% endif %}
        </div>
      </div>
    </nav>
    <p></p>
    <div class="row">
        <div class="col">
        {% block content %}

        {% endblock %}

        </div>
    </div>
</div>
</body>
</html>